theme="material-design"
baseurl = "http://quanfeng.tech/snippets"
languageCode = "zh-CN"
title = "frontend snippets"
MetaDataFormat = "toml"
paginate = 10 # To specify a multiple of 3
disqusShortname = "Your Disqus Name" # optional
copyright = "© 2018 Copyright 0326"

[params]
  description = "前端工程师日常技术片段" # optional
  github = "Your Github Name" # optional
  facebook = "Your facebook Name" # optional
  gplus = "Your Google+ profile name" # optional
  linkedin = "Your LinkedIn Name" # optional
  headerCover = "images/headerCover.png" # optional
  footerCover = "images/footerCover.png" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional